# Generated by Django 6.0 on 2026-06-27 16:57

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Каталог туров',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('tour', models.CharField(blank=True, max_length=200, verbose_name='Интересующий тур')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('location', models.CharField(help_text='Например: Индонезия · Бали', max_length=120, verbose_name='Локация')),
                ('summary', models.TextField(verbose_name='Краткое описание')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Подробное описание')),
                ('highlights', wagtail.fields.StreamField([('item', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {})}, verbose_name='Особенности тура')),
                ('duration', models.CharField(max_length=40, verbose_name='Длительность')),
                ('group_size', models.CharField(max_length=40, verbose_name='Размер группы')),
                ('group_size_max', models.PositiveSmallIntegerField(default=8, verbose_name='Макс. мест')),
                ('comfort', models.CharField(default='Бутик-виллы', max_length=60, verbose_name='Проживание')),
                ('difficulty', models.CharField(default='Лёгкая', max_length=40, verbose_name='Сложность')),
                ('price_from', models.CharField(max_length=40, verbose_name='Цена от')),
                ('country_tag', models.CharField(choices=[('bali', 'Бали'), ('japan', 'Япония'), ('vietnam', 'Вьетнам')], default='bali', max_length=20, verbose_name='Тег страны')),
                ('hero_images', wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, verbose_name='Галерея (3–5 фото)')),
                ('itinerary', wagtail.fields.StreamField([('day', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: День 1', 'label': 'День'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок дня'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Описание'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фото дня', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('day_number', 0), ('title', 1), ('description', 2), ('image', 3)]], {})}, verbose_name='Программа по дням')),
                ('accommodation', wagtail.fields.StreamField([('item', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Название отеля/виллы'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: Бутик-вилла · 3 ночи', 'label': 'Тип и ночи'}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Описание'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фото', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('type', 1), ('description', 2), ('image', 3)]], {})}, verbose_name='Проживание')),
                ('included', wagtail.fields.StreamField([('item', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {})}, verbose_name='Включено')),
                ('excluded', wagtail.fields.StreamField([('item', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {})}, verbose_name='Не включено')),
                ('cancel_policy', wagtail.fields.StreamField([('item', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: За 30+ дней', 'label': 'Период'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Описание'}), 2: ('wagtail.blocks.IntegerBlock', (), {'label': 'Возврат (%)', 'max_value': 100, 'min_value': 0}), 3: ('wagtail.blocks.StructBlock', [[('period', 0), ('description', 1), ('refund_percent', 2)]], {})}, verbose_name='Политика отмены')),
            ],
            options={
                'verbose_name': 'Страница тура',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Вступление')),
                ('email', models.EmailField(default='hello@tochka.travel', max_length=254, verbose_name='Email')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('whatsapp', models.URLField(blank=True, verbose_name='WhatsApp')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адрес')),
                ('hours', models.CharField(blank=True, max_length=120, verbose_name='Часы работы')),
                ('side_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фото сбоку')),
            ],
            options={
                'verbose_name': 'Страница контактов',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_eyebrow', models.CharField(default='Авторские маршруты по Азии', max_length=120, verbose_name='Надзаголовок')),
                ('hero_title', models.CharField(default='Замедлись, чтобы услышать Азию', max_length=160, verbose_name='Заголовок')),
                ('hero_subtitle', models.TextField(blank=True, verbose_name='Подзаголовок')),
                ('hero_cta_text', models.CharField(default='Смотреть направления', max_length=60, verbose_name='Текст CTA')),
                ('body', wagtail.fields.StreamField([('manifest', 8), ('destinations', 14), ('quote', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': '01', 'label': 'Цифра'}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'Философия пути', 'label': 'Надзаголовок'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок'}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'label': 'Текст'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Значение'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись'}), 6: ('wagtail.blocks.StructBlock', [[('value', 4), ('label', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Метрики'}), 8: ('wagtail.blocks.StructBlock', [[('numeral', 0), ('eyebrow', 1), ('heading', 2), ('body', 3), ('stats', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Направление'}), 10: ('wagtail.blocks.TextBlock', (), {'label': 'Описание (до 160 симв.)', 'max_length': 160}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: от $2 500', 'label': 'Цена от'}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фото'}), 13: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка на страницу каталога', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('title', 9), ('description', 10), ('price_from', 11), ('image', 12), ('link', 13)]], {}), 15: ('wagtail.blocks.TextBlock', (), {'label': 'Цитата'}), 16: ('wagtail.blocks.CharBlock', (), {'label': 'Автор / маршрут'}), 17: ('wagtail.blocks.StructBlock', [[('quote', 15), ('author', 16)]], {})}, verbose_name='Секции')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Главное фото')),
            ],
            options={
                'verbose_name': 'Главная страница',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TourDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата заезда')),
                ('end_date', models.DateField(verbose_name='Дата выезда')),
                ('price', models.PositiveIntegerField(verbose_name='Цена (USD)')),
                ('total_spots', models.PositiveSmallIntegerField(default=8, verbose_name='Всего мест')),
                ('spots_left', models.PositiveSmallIntegerField(default=8, verbose_name='Свободных мест')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_dates', to='tours.tourpage')),
            ],
            options={
                'verbose_name': 'Дата заезда',
                'verbose_name_plural': 'Даты заездов',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='TourPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='tours.tourpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tourpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='tours.TourPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
