# Generated by Django 6.0 on 2026-06-27 18:21

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='Одна строка под заголовком', verbose_name='Краткое описание')),
                ('content', wagtail.fields.RichTextField(verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Правовой документ',
                'verbose_name_plural': 'Правовые документы',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='tourpage',
            name='cta_button',
            field=models.CharField(default='Выбрать дату', max_length=60, verbose_name='Текст кнопки CTA'),
        ),
        migrations.AddField(
            model_name='tourpage',
            name='cta_heading',
            field=models.CharField(default='Готовы почувствовать настоящую Азию?', max_length=160, verbose_name='Заголовок финального CTA'),
        ),
        migrations.AddField(
            model_name='tourpage',
            name='faq',
            field=wagtail.fields.StreamField([('item', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Вопрос'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Ответ'}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {})}, verbose_name='Частые вопросы (FAQ)'),
        ),
        migrations.AddField(
            model_name='tourpage',
            name='force_majeure_note',
            field=models.TextField(blank=True, default='При форс-мажоре (стихийные бедствия, закрытие границ) возврат — 100% независимо от срока.', verbose_name='Сноска о форс-мажоре'),
        ),
        migrations.AddField(
            model_name='tourpage',
            name='what_to_bring',
            field=wagtail.fields.StreamField([('item', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Пункт'})}, verbose_name='Что взять с собой'),
        ),
        migrations.AlterField(
            model_name='tourpage',
            name='itinerary',
            field=wagtail.fields.StreamField([('day', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Один день: «1», диапазон: «1-2». «День» добавляется автоматически.', 'label': 'Номер дня / диапазон'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок дня'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Описание'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фото дня', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('day_number', 0), ('title', 1), ('description', 2), ('image', 3)]], {})}, verbose_name='Программа по дням'),
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, verbose_name='Вступление')),
                ('about_text', wagtail.fields.RichTextField(blank=True, verbose_name='О нас (подробно)')),
                ('company_full_name', models.CharField(blank=True, max_length=400, verbose_name='Полное юридическое наименование')),
                ('legal_address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('actual_address', models.TextField(blank=True, verbose_name='Фактический адрес')),
                ('ogrn', models.CharField(blank=True, max_length=20, verbose_name='ОГРН')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('is_operator', models.BooleanField(default=False, verbose_name='Является туроператором')),
                ('registry_number', models.CharField(blank=True, help_text='Например: РТО-000001', max_length=50, verbose_name='Реестровый номер ЕФР туроператоров')),
                ('financial_guarantee', models.TextField(blank=True, help_text='Размер и наименование организации-гаранта', verbose_name='Финансовое обеспечение')),
                ('partners', wagtail.fields.StreamField([('partner', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Туроператор'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: РТО-000001', 'label': 'Реестровый номер ЕФР', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'Сайт', 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Продукт / что реализуете', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('registry_number', 1), ('website', 2), ('description', 3)]], {})}, verbose_name='Туроператоры-партнёры (принципалы)')),
                ('certificates', wagtail.fields.StreamField([('cert', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Название'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Организация / реестр', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Номер / дата', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Ссылка для проверки', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('issuer', 1), ('number', 2), ('url', 3)]], {})}, verbose_name='Сертификаты и членство в ассоциациях')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фото для hero')),
            ],
            options={
                'verbose_name': 'О компании',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TourGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Фото')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='tours.tourpage')),
            ],
            options={
                'verbose_name': 'Фото галереи',
                'verbose_name_plural': 'Фото галереи',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
