# Generated by Django 6.0 on 2026-06-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_legalpage_tourpage_cta_button_tourpage_cta_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='bank_bik',
            field=models.CharField(blank=True, max_length=9, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='bank_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город банка'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='bank_corr',
            field=models.CharField(blank=True, max_length=20, verbose_name='Корр. счёт'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='bank_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='bank_settlement',
            field=models.CharField(blank=True, max_length=20, verbose_name='Расчётный счёт'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='inn',
            field=models.CharField(blank=True, max_length=15, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='ogrn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ОГРН / ОГРНИП'),
        ),
    ]
