# Generated by Django 6.0 on 2026-07-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_aboutpage_bank_bik_aboutpage_bank_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdate',
            name='currency',
            field=models.CharField(choices=[('RUB', '₽ Рубли'), ('USD', '$ Доллары'), ('EUR', '€ Евро')], default='RUB', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='tourdate',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
    ]
