# Generated by Django 6.0 on 2026-07-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_add_about_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpage',
            name='country_tag',
            field=models.CharField(choices=[('bali', 'Бали'), ('japan', 'Япония'), ('vietnam', 'Вьетнам'), ('china', 'Китай')], default='bali', max_length=20, verbose_name='Тег страны'),
        ),
    ]
