# Generated by Django 6.0 on 2026-07-25 13:53

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_add_china_country_tag'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryRulesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Вступление')),
                ('countries', wagtail.fields.StreamField([('country', 7)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('vietnam', 'Вьетнам'), ('indonesia', 'Индонезия'), ('china', 'Китай'), ('cambodia', 'Камбоджа'), ('japan', 'Япония'), ('laos', 'Лаос'), ('malaysia', 'Малайзия'), ('nepal', 'Непал'), ('philippines', 'Филиппины'), ('thailand', 'Таиланд'), ('korea', 'Южная Корея')], 'label': 'Страна'}), 1: ('wagtail.blocks.BooleanBlock', (), {'label': 'Без визы', 'required': False}), 2: ('wagtail.blocks.BooleanBlock', (), {'label': 'Виза по прилёте', 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'label': 'E-visa', 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'label': 'Виза заранее', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: 30 дней, 90 дней', 'label': 'Макс. срок пребывания', 'required': False}), 6: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'label': 'Примечания', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('country', 0), ('visa_free', 1), ('visa_on_arrival', 2), ('e_visa', 3), ('visa_required', 4), ('max_stay', 5), ('notes', 6)]], {})}, verbose_name='Страны')),
            ],
            options={
                'verbose_name': 'Правила въезда',
                'verbose_name_plural': 'Правила въезда',
            },
            bases=('wagtailcore.page',),
        ),
    ]
