# Generated by Django 6.0 on 2026-07-25 15:01

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_entryrulespage_hero_image'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryRuleCountryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('country_code', models.CharField(choices=[('vietnam', 'Вьетнам'), ('indonesia', 'Индонезия'), ('china', 'Китай'), ('cambodia', 'Камбоджа'), ('japan', 'Япония'), ('laos', 'Лаос'), ('malaysia', 'Малайзия'), ('nepal', 'Непал'), ('philippines', 'Филиппины'), ('thailand', 'Таиланд'), ('korea', 'Южная Корея')], max_length=20, unique=True, verbose_name='Код страны')),
                ('visa_free', models.BooleanField(default=False, verbose_name='Без визы')),
                ('visa_on_arrival', models.BooleanField(default=False, verbose_name='Виза по прилёте')),
                ('e_visa', models.BooleanField(default=False, verbose_name='E-visa')),
                ('visa_required', models.BooleanField(default=False, verbose_name='Виза заранее')),
                ('max_stay', models.CharField(blank=True, max_length=100, verbose_name='Макс. срок пребывания')),
                ('notes', wagtail.fields.RichTextField(blank=True, verbose_name='Примечания')),
                ('flag_image', models.ForeignKey(blank=True, help_text='Рекомендуемый формат: SVG или PNG с прозрачным фоном', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Флаг страны (SVG/PNG)')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фото для hero')),
            ],
            options={
                'verbose_name': 'Правила въезда — страна',
                'verbose_name_plural': 'Правила въезда — страны',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EntryRulesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Вступление')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фото для hero')),
            ],
            options={
                'verbose_name': 'Правила въезда (главная)',
                'verbose_name_plural': 'Правила въезда (главная)',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='EntryRulesPage',
        ),
    ]
