# Generated by Django 6.0 on 2026-08-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_entryrulecountrypage_entryrulesindexpage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='email',
            field=models.EmailField(default='Tochkanacarte@yandex.ru', max_length=254, verbose_name='Email'),
        ),
    ]
