# Generated by Django 6.0 on 2026-08-08 10:04

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_alter_contactpage_email'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageTourPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('location', models.CharField(help_text='Например: Вьетнам · Дананг · Нячанг · Фукуок', max_length=120, verbose_name='Локация')),
                ('summary', models.TextField(verbose_name='Краткое описание')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('duration', models.CharField(max_length=60, verbose_name='Длительность')),
                ('price_from', models.CharField(max_length=40, verbose_name='Цена от')),
                ('country_tag', models.CharField(choices=[('bali', 'Бали'), ('japan', 'Япония'), ('vietnam', 'Вьетнам'), ('china', 'Китай')], default='vietnam', max_length=20, verbose_name='Тег страны')),
                ('hero_images', wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, verbose_name='Галерея (3–5 фото)')),
                ('hotel_sections', wagtail.fields.StreamField([('section', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Курорт'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Название отеля/виллы'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: Бутик-вилла · 3 ночи', 'label': 'Тип и ночи'}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Описание'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фото', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('name', 1), ('type', 2), ('description', 3), ('image', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'label': 'Отели'}), 7: ('wagtail.blocks.StructBlock', [[('resort', 0), ('hotels', 6)]], {})}, verbose_name='Отели по курортам')),
                ('cta_heading', models.CharField(default='Подберём тур, который подойдёт именно вам', max_length=160, verbose_name='Заголовок финального CTA')),
                ('cta_button', models.CharField(default='Подобрать тур', max_length=60, verbose_name='Текст кнопки CTA')),
            ],
            options={
                'verbose_name': 'Пакетный тур',
                'verbose_name_plural': 'Пакетные туры',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
