# Generated by Django 6.0 on 2026-08-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_packagetourpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpage',
            name='dates_info',
            field=models.TextField(blank=True, help_text='Например: Любые даты до 12.12.26', verbose_name='Даты заездов (инфо)'),
        ),
    ]
