# Generated by Django 6.0 on 2026-08-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_tourpage_dates_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория тура',
                'verbose_name_plural': 'Категории туров',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='packagetourpage',
            name='country_tag',
            field=models.CharField(choices=[('bali', 'Бали'), ('indonesia', 'Индонезия'), ('malaysia', 'Малайзия'), ('japan', 'Япония'), ('vietnam', 'Вьетнам'), ('china', 'Китай')], default='vietnam', max_length=20, verbose_name='Тег страны'),
        ),
        migrations.AlterField(
            model_name='tourpage',
            name='country_tag',
            field=models.CharField(choices=[('bali', 'Бали'), ('indonesia', 'Индонезия'), ('malaysia', 'Малайзия'), ('japan', 'Япония'), ('vietnam', 'Вьетнам'), ('china', 'Китай')], default='bali', max_length=20, verbose_name='Тег страны'),
        ),
        migrations.AddField(
            model_name='tourpage',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Например: тур «Бали + Комодо» можно отнести и к Бали, и к Индонезии.', related_name='tours', to='tours.tourcategory', verbose_name='Категории (несколько)'),
        ),
    ]
