# Generated by Django 6.0 on 2026-08-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_tourcategory_alter_packagetourpage_country_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagetourpage',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='tourpage',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
    ]
